# Generated by Django 5.0.6 on 2024-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
            ],
        ),
    ]
